<?
$GLOBALS["codekeepers_block_id"] = array(
    'banners_banner_main_id' => '#BANNER_MAIN_IBLOCK_ID#',
    'catalog_goods_id' => '#GOODS_IBLOCK_ID#',
    'content_features_under_id' => '#FEATURES_UNDER_IBLOCK_ID#',
    'content_services_id' => '#SERVICES_IBLOCK_ID#',
    'content_team_id' => '#TEAM_IBLOCK_ID#',
    'content_blog_id' => '#BLOG_IBLOCK_ID#',
    'content_sidebar-phone_id' => '#SIDEBAR-PHONE_IBLOCK_ID#',
    'content_projects_id' => '#PROJECTS_IBLOCK_ID#',
    'content_reviews_id' => '#REVIEWS_IBLOCK_ID#',
    'content_about_id' => '#ABOUT_IBLOCK_ID#',
    'content_features_id' => '#FEATURES_IBLOCK_ID#',
    'content_partners_id' => '#PARTNERS_IBLOCK_ID#',
    'content_call-to-action_id' => '#CALL-TO-ACTION_IBLOCK_ID#',
    'content_faq_id' => '#FAQ_IBLOCK_ID#',
    'content_timeline_id' => '#TIMELINE_IBLOCK_ID#',
    'content_why-us_id' => '#WHY-US_IBLOCK_ID#',
    'content_stats_id' => '#STATS_IBLOCK_ID#',
    'content_vacancies_id' => '#VACANCIES_IBLOCK_ID#',
    'content_discount_id' => '#DISCOUNT_IBLOCK_ID#',
    'content_licence_id' => '#LICENCE_IBLOCK_ID#',
    'content_contacts_id' => '#CONTACTS_IBLOCK_ID#',
    'content_discounts_id' => '#DISCOUNTS_IBLOCK_ID#',
    'content_timeline-block_id' => '#TIMELINE-BLOCK_IBLOCK_ID#',
    'settings_messengers_id' => '#MESSENGERS_IBLOCK_ID#',
    'settings_main_id' => '#MAIN_SETTINGS_IBLOCK_ID#',
    'settings_main_element_id' => '#MAIN_SETTINGS_ELEMENT_ID#',
    'requests_feedback_id' => '#FEEDBACK_IBLOCK_ID#',
)
?>